# Creates a prod GCP environment for working on the Cloud Resume Challenge
name: deploy-prod-environment

# Controls when the workflow will run
on:
  # Triggers on push to any non-main branch
  push:
    branches:
      - main

  # Allow for manually deploying the DEV env, as we may want to be able to turn it on and off later.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: terraform/prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/357366557592/locations/global/workloadIdentityPools/prod-pool/providers/prod-provider
          service_account: terraform-cloud@cloud-resume-prod.iam.gserviceaccount.com

      # Runs a set of commands using the runners shell
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -var image_tag=1.0.0 -auto-approve -input=false
