# Creates a dev GCP environment for working on the Cloud Resume Challenge
# This workflow does NOT automatically destroy the env when you're done
# Be sure to trigger the destroy workflow after to avoid sad wallets

name: deploy-dev-environment

# Controls when the workflow will run
on:
  # Triggers on push to any non-main branch
  push:
    branches-ignore:
      - main

  # Allow for manually deploying the DEV env, as we may want to be able to turn it on and off later.
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform/dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
