# Creates a uat GCP environment for working on the Cloud Resume Challenge

name: deploy-uat-environment

# Controls when the workflow will run
on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform/uat

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    environment: uat

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Trigger CodeCov, to be expanded further in future commits
      - uses: codecov/codecov-action@v3

      # Runs a set of commands using the runners shell
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
