# Destroys all resources created in the Dev GCP environment
name: dev-destroy-resume

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform/dev

jobs:
  destroy:
    name: Destroy GCP Dev Environment
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
