# Destroys all resources created in the UAT GCP environment when PR is merged to main
name: destroy-uat-environment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

defaults:
  run:
    working-directory: terraform/uat

jobs:
  destroy:
    name: Destroy GCP UAT Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          environment: uat

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Update deployment status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment: uat
          state: inactive
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
