# Destroys all resources created in the UAT GCP environment when PR is merged to main
name: destroy-uat-environment

on:
  push:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform/uat

jobs:
  destroy:
    name: Destroy GCP UAT Environment
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
