# Destroys all resources created in the Dev GCP environment
name: destroy-dev-environment

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write

defaults:
  run:
    working-directory: terraform/dev

jobs:
  destroy:
    name: Destroy GCP Dev Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/460847146789/locations/global/workloadIdentityPools/dev-pool/providers/dev-provider
          service_account: terraform-cloud@cloud-resume-dev.iam.gserviceaccount.com

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{ github.token }}
          environment: dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Update deployment status
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ github.token }}
          environment: dev
          state: inactive
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
