# Creates a dev GCP environment for working on the Cloud Resume Challenge
# This workflow does NOT automatically destroy the env when you're done
# Be sure to trigger the destroy workflow after to avoid sad wallets

name: dev-deploy-resume

# Controls when the workflow will run
on:
  # Triggers on push to any non-main branch
  push:
    branches-ignore:
      - main

  # Allow for manually deploying the DEV env, as we may want to be able to turn it on and off later.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: This is a placeholder for later
        run: |
          echo We're not using the build phase just yet
          echo do we wanna do unit tests in dev?
          echo Soon, we'll have some Docker and NextJS to play with here!
          echo This is the beginning of something neat
